name: Android CI

on:
  push:
    branches:
      - *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execution permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Run detekt validation
        run: ./gradlew detekt